all:
	make -C ./api all
	make -C ./ncurses all
	make -C ./app all
dev:
	make -C ./api dev
	make -C ./ncurses dev
	make -C ./app dev
install:
	make -C ./app install
uninstall:
	make -C ./api remove
clean:
	make -C ./api clean
	make -C ./app clean
	make -C ./ncurses clean
